zookeeper {
  basePath = "/snack/serviceDiscovery"
  connectString = "localhost:2181"
}
server {
  port = 8080
  name = "com.snack.web.demo"
}
rpc {
  invoke.timeout = 5000
  invoke.retry.enable = true
}
tracing {
  enabled = true
  sampleRate = 100
}
spring {
  output.ansi.enabled = NEVER
}
