zookeeper {
  basePath = "/snack/serviceDiscovery"
  connectString = "localhost:2181"
}
server {
  port = 9999
  name = "com.snack.demo.service"
}
tracing {
  enabled = true
  sampleRate = 100
}
spring {
  output.ansi.enabled = NEVER
}
